spring.application.name=application-service

spring.datasource.url=jdbc:postgresql://localhost:5434/application-service
spring.datasource.username=postgres
spring.datasource.password=123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8084


eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# C?u hình Retry cho instance có tên là jobServiceRetry
resilience4j.retry.instances.jobServiceRetry.maxAttempts=3
resilience4j.retry.instances.jobServiceRetry.waitDuration=3s
resilience4j.retry.instances.jobServiceRetry.enableExponentialBackoff=true
resilience4j.retry.instances.jobServiceRetry.exponentialBackoffMultiplier=2
logging.level.io.github.resilience4j=DEBUG

# Option: Danh sách các exception s? kích ho?t retry
resilience4j.retry.instances.jobServiceRetry.retryExceptions[0]=feign.RetryableException
resilience4j.retry.instances.jobServiceRetry.retryExceptions[1]=java.util.concurrent.TimeoutException
resilience4j.retry.instances.jobServiceRetry.retryExceptions[2]=org.springframework.web.client.ResourceAccessException

# AI Configuration
OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
OPENAI_BASE_URL=${OPENAI_BASE_URL}/v1
OPENAI_MODEL=${AI_MODEL}

