spring.application.name=notification-service

server.port=8085

spring.data.mongodb.uri=${MONGO_URI}
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false


logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG


management.endpoints.web.exposure.include=*

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

spring.jackson.time-zone=Asia/Ho_Chi_Minh

# Mail configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.consumer.group-id=${KAFKA_CONSUMER_GROUP_ID:notification-group-v3}
spring.kafka.consumer.auto-offset-reset=latest

spring.kafka.consumer.key-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.key.delegate.class=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.use.type.headers=true
spring.kafka.consumer.properties.spring.json.type.mapping=orderPaymentSuccessEvent:iuh.fit.notificationservice.event.OrderPaymentSuccessEvent,employerJobStatusChangedEvent:iuh.fit.notificationservice.event.EmployerJobStatusChangedEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=*

# Resilience4j Configuration
resilience4j.retry.instances.emailService.maxAttempts=3
resilience4j.retry.instances.emailService.waitDuration=2s
resilience4j.retry.instances.emailService.enableExponentialBackoff=true
resilience4j.retry.instances.emailService.exponentialBackoffMultiplier=2

resilience4j.circuitbreaker.instances.emailService.slidingWindowSize=3
resilience4j.circuitbreaker.instances.emailService.failureRateThreshold=50
resilience4j.circuitbreaker.instances.emailService.minimumNumberOfCalls=2
resilience4j.circuitbreaker.instances.emailService.waitDurationInOpenState=30s
resilience4j.circuitbreaker.instances.emailService.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.instances.emailService.registerHealthIndicator=true

# Logging Level for Resilience4j
logging.level.io.github.resilience4j=DEBUG
