spring.application.name=notification-service

server.port=8085

spring.data.mongodb.uri=${MONGO_URI}
spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false


logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG


management.endpoints.web.exposure.include=*


spring.jackson.time-zone=Asia/Ho_Chi_Minh