spring.application.name=job-service

spring.datasource.url=jdbc:postgresql://localhost:5434/job-service
spring.datasource.username=postgres
spring.datasource.password=doyouam123


spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Fix: force dùng 127.0.0.1 thay vì WSL2 network adapter (172.x.x.x)
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false

spring.cache.type=redis
spring.cache.redis.time-to-live=300000
spring.cache.redis.use-key-prefix=true
spring.cache.redis.key-prefix=job-service::
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=employerJobStatusChangedEvent:iuh.fit.jobservice.event.EmployerJobStatusChangedEvent

spring.ai.openai.api-key=${OPENROUTER_API_KEY}
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.options.model=openai/gpt-oss-120b:free
spring.ai.openai.chat.options.max-tokens=1000
