
spring.application.name=user-service

spring.datasource.url=jdbc:postgresql://localhost:5432/user-service
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
server.port=8083

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=false
jwt.signer-key=8c37d35651c4f1a0e373e08cd6eababff9903dc1aeb20581fc9f56a302c6cf60