name: Deploy Backend to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            cd ${{ secrets.APP_DIR }}

            git fetch origin
            git checkout develop
            git pull origin develop

            docker network create career-net || true

            docker compose up -d --build postgres-server redis zookeeper kafka eureka-server user-service company-service job-service api-gateway

            docker image prune -f
